import {
    CheckCircle2,
    AlertTriangle,
    Rocket,
} from "lucide-react";

const sections = [
    {
        title: "Strengths",
        key: "strengths",
        icon: CheckCircle2,
        iconColor: "text-emerald-600",
        bg: "bg-emerald-50",
        border: "border-emerald-100",
    },
    {
        title: "Risks",
        key: "weaknesses",
        icon: AlertTriangle,
        iconColor: "text-orange-600",
        bg: "bg-orange-50",
        border: "border-orange-100",
    },
    {
        title: "Improvements",
        key: "improvements",
        icon: Rocket,
        iconColor: "text-violet-600",
        bg: "bg-violet-50",
        border: "border-violet-100",
    },
];

export default function EngineeringInsights({ project }) {

    return (

        <section className="mt-8">

            <div className="mb-6">

                <h2 className="text-2xl font-bold">

                    AI Engineering Insights

                </h2>

                <p className="mt-2 text-slate-500">

                    Key strengths, engineering risks and recommendations
                    generated by CareerOS AI.

                </p>

            </div>

            <div className="grid gap-6 lg:grid-cols-3">

                {sections.map((section) => {

                    const Icon = section.icon;

                    return (

                        <div
                            key={section.key}
                            className={`
                                rounded-3xl
                                border
                                ${section.border}
                                ${section.bg}
                                p-7
                            `}
                        >

                            <div className="flex items-center gap-3">

                                <Icon
                                    className={`
                                        h-6
                                        w-6
                                        ${section.iconColor}
                                    `}
                                />

                                <h3
                                    className="
                                        text-xl
                                        font-semibold
                                    "
                                >
                                    {section.title}
                                </h3>

                            </div>

                            <div className="mt-6 space-y-4">

                                {(project[section.key] ?? []).map((item) => (

                                    <div
                                        key={item}
                                        className="
                                            rounded-xl
                                            bg-white
                                            p-4
                                            shadow-sm
                                        "
                                    >

                                        <p
                                            className="
                                                leading-7
                                                text-slate-700
                                            "
                                        >
                                            {item}
                                        </p>

                                    </div>

                                ))}

                            </div>

                        </div>

                    );

                })}

            </div>

        </section>

    );

}