import {
    Award,
    BadgeCheck,
    Briefcase,
    CheckCircle2,
    Sparkles,
} from "lucide-react";

export default function FinalRecommendation({ project }) {

    return (

        <section
            className="
                mt-8
                rounded-3xl
                bg-gradient-to-br
                from-violet-700
                via-violet-600
                to-indigo-700
                p-10
                text-white
                shadow-xl
            "
        >

            <div className="flex items-center gap-4">

                <div className="rounded-2xl bg-white/20 p-4">

                    <Sparkles className="h-8 w-8" />

                </div>

                <div>

                    <h2 className="text-3xl font-bold">

                        Final AI Recommendation

                    </h2>

                    <p className="mt-2 text-violet-100">

                        Executive summary generated by CareerOS AI.

                    </p>

                </div>

            </div>

            <div
                className="
                    mt-10
                    grid
                    gap-6
                    lg:grid-cols-2
                "
            >

                <div className="space-y-6">

                    <div className="rounded-2xl bg-white/10 p-6">

                        <div className="flex items-center gap-3">

                            <Award className="h-6 w-6" />

                            <h3 className="text-lg font-semibold">

                                Engineering Maturity

                            </h3>

                        </div>

                        <p className="mt-4 leading-8">

                            {project.maturityStage}

                        </p>

                        <div className="mt-5 h-3 rounded-full bg-white/20">

                            <div
                                className="h-3 rounded-full bg-white"
                                style={{
                                    width: `${project.maturityScore ?? 0}%`,
                                }}
                            />

                        </div>

                        <p className="mt-2 text-sm text-violet-100">

                            {project.maturityScore}/100

                        </p>

                    </div>

                    <div className="rounded-2xl bg-white/10 p-6">

                        <div className="flex items-center gap-3">

                            <BadgeCheck className="h-6 w-6" />

                            <h3 className="text-lg font-semibold">

                                Repository Confidence

                            </h3>

                        </div>

                        <p className="mt-4 leading-8">

                            {project.repositoryConfidence}

                        </p>

                    </div>

                </div>

                <div className="space-y-6">

                    <div className="rounded-2xl bg-white/10 p-6">

                        <div className="flex items-center gap-3">

                            <Briefcase className="h-6 w-6" />

                            <h3 className="text-lg font-semibold">

                                Hiring Recommendation

                            </h3>

                        </div>

                        <p className="mt-4 leading-8">

                            {project.hiringRecommendation}

                        </p>

                    </div>

                    <div className="rounded-2xl bg-white/10 p-6">

                        <div className="flex items-center gap-3">

                            <CheckCircle2 className="h-6 w-6" />

                            <h3 className="text-lg font-semibold">

                                Portfolio Recommendation

                            </h3>

                        </div>

                        <p className="mt-4 leading-8">

                            {project.portfolioRecommendation}

                        </p>

                    </div>

                </div>

            </div>

            <div
                className="
                    mt-10
                    rounded-2xl
                    bg-white
                    p-8
                    text-slate-800
                "
            >

                <h3 className="text-2xl font-bold">

                    Final Verdict

                </h3>

                <p
                    className="
                        break-words
                        mt-4
                        leading-8
                        text-slate-600

                    "
                >
                    {project.finalEngineeringReview}
                </p>

            </div>

        </section>

    );

}