spring.application.name=careeros-backend
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/careeros_db}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:demo}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
gemini.api.key=${GEMINI_API_KEY:}
rapidapi.key=${RAPIDAPI_KEY:}
adzuna.app.id=${ADZUNA_APP_ID}
adzuna.api.key=${ADZUNA_API_KEY}
youtube.api.key=${YOUTUBE_API_KEY:}